disp(strcat("Loading data..."," - ",ctime(time())));
load("dbConverted_Beator.mat");
beatorData.supplied = appdata.data.supplied;
beatorData.targetDB = appdata.data.site.targetDB;
save -zip dataBeator.mat beatorData;
clear appdata;
load("dbConverted_Peukert.mat");
peukertData.supplied = appdata.data.supplied;
peukertData.targetDB = appdata.data.site.targetDB;
save -zip dataPeukert.mat peukertData;
clear appdata;
load("dbConverted_Franke.mat");
frankeData.supplied = appdata.data.supplied;
frankeData.targetDB = appdata.data.site.targetDB;
save -zip dataFranke.mat frankeData;
clear appdata;
load("dbConverted_Mast.mat");
mastData.supplied = appdata.data.supplied;
mastData.targetDB = appdata.data.site.targetDB;
save -zip dataMast.mat mastData;
clear appdata;
load("dbConverted_Tietgen.mat");
tietgenData.supplied = appdata.data.supplied;
tietgenData.targetDB = appdata.data.site.targetDB;
save -zip dataTietgen.mat tietgenData;
clear appdata;
disp(strcat("...done", " - ", ctime(time())));