function targetDBstandort = GenerateTargetDB(mySize)
  targetDBstandort = cell(mySize,26);                                             #Import aus ASZPM-Feld
  targetDBstandort(1,1) = "StandortID";                                           #N/A
  targetDBstandort(1,2) = "StandortKennungExtern";                                #N/A
  targetDBstandort(1,3) = "StandortKennungIntern";                                #N/A
  targetDBstandort(1,4) = "Anlage_ASZPMID";                                       #AnlageID | 1
  targetDBstandort(1,5) = "LabbaseStandortID";                                    #AuftraggeberID | 3 --- svenja
  targetDBstandort(1,6) = "Rechnungsempfänger_LabbaseID";                         #N/A
  targetDBstandort(1,7) = "UsI_LABbaseID";                                        #Usl_LABbaseID | 10
  targetDBstandort(1,8) = "Kunde_LABbaseID";                                      #Kunde_LABbaseID | 14
  targetDBstandort(1,9) = "KundeAlt";                                             #KundeAlt | 15
  targetDBstandort(1,10) = "KundeWechselDatum";                                   #DatumWechselKunde | 17 !!!DATETIME!!!
  targetDBstandort(1,11) = "Objektbezeichnung";                                   #Objektbezeichnung | 18
  targetDBstandort(1,12) = "Straße";                                              #Objektadresse | 19, 26 ist zu priorisieren
  targetDBstandort(1,13) = "Hausnummer";                                          #Hausnummer | 20
  targetDBstandort(1,14) = "PLZ";                                                 #Postleitzahl | 21
  targetDBstandort(1,15) = "Ort";                                                 #Ort | 22
  targetDBstandort(1,16) = "GebäudeArtID";                                        #GebäudeartID | 28 --- svenja
  targetDBstandort(1,17) = "AnsprechpartnerVOName";                               #[Ansprechpartner/Hausmeister] | 29 ---mibi
  targetDBstandort(1,18) = "AnsprechpartnerVOTelefon";                            #N/A ---mibi
  targetDBstandort(1,19) = "AnsprechpartnerVOEMail";                              #N/A ---mibi
  targetDBstandort(1,20) = "KundenkontaktName";                                   #N/A ---mibi
  targetDBstandort(1,21) = "KundenkontaktTelefon";                                #N/A ---mibi
  targetDBstandort(1,22) = "KundenkontaktEMail";                                  #N/A ---mibi
  targetDBstandort(1,23) = "Bemerkung";                                           #[HV-Kontakt] | 32 ---mibi
  targetDBstandort(1,24) = "KundenbetreuerVorbelegungID";                         #N/A
  targetDBstandort(1,25) = "NächsterTermin";                                      #MaxSollTermin | 37 !!!DATETIME!!!
  targetDBstandort(1,26) = "AnlageAdressePrüfen";                                 #Flag vom Bearbeiter gesetzt
endfunction